### ISSUE TITLE
Playback stops before end of podcast

### ISSUE THREAD

**Issue by Mebus** [tkem/mopidy-podcast#25]
Hallo,

I am using mopidy-podcast with the WDR5 Leonardo Podcast:

http://www1.wdr.de/radio/podcasts/wdr5/leonardo302.podcast

on a raspberry pi. But the playback of the podcast always stops before the actual end.

Is this a bug? Can this be fixed?

Mebus

**Comment by tkem** [comment]
Is there any log output?

**Comment by Mebus** [comment]
In the mopidy.log file this was logged after I started the podcast and before it stopped playing:

2015-06-16 08:50:29,746 WARNING [2723:MainThread] mopidy.audio.gst: Das Element kann diesen Datenstrom nicht verarbeiten. Bitte schicken Sie einen Fehlerbericht.
2015-06-16 08:50:30,287 INFO [2723:HttpServer] root: 200 GET /musicbox_webclient/images/icons/play_alt_12x12.png (127.0.0.1) 56.94ms

Mebus

**Comment by tkem** [comment]
This isn't caused by Mopidy-Podcast, but looks more like a gstreamer issue. Either you're missing a gstreamer plugin, or the stream cannot be handled by gstreamer-0.10 used by Mopidy core.

There's some information on debugging gstreamer problems in the Mopidy docs [https://docs.mopidy.com/en/latest/troubleshooting/?highlight=gstreamer], but I'd suggest you post this in the Mopidy discussion forum [https://discuss.mopidy.com/]. Dort werden Sie geholfen ;-)
