### ISSUE TITLE
No Podcasts shown 

### ISSUE THREAD

**Issue by deisi** [tkem/mopidy-podcast#28]
Hi

I don't know if this is the right place to ask, but apparently I'm not able to get mopidy-podcast up and running. My mopidy.config contains:

    [podcast]
    enabled = true
    #browse_limit = 100
    #search_limit = 20
    search_details = on
    #update_interval = 86400
    feeds =
        http://www.radioeins.de/archiv/podcast/zwei_alte_hasen.feed.podcast.xml
        http://www1.wdr.de/radio/podcasts/wdr5/zeitzeichen244.podcast
        http://www.npr.org/rss/podcast.php?id=510019
        http://www.npr.org/rss/podcast.php?id=510253
        http://www.npr.org/rss/podcast.php?id=510306
    #feeds_root_name = Zeitzeichen
    #feeds_cache_size = 32
    #feeds_cache_ttl = 3600
    #feeds_timeout = 10

I left the default feeds, hoping they still work and I should see something. However, no podcast appears within the Subscribed Feeds category.

I also installed the ITunes extension, but the same happens. I can browse down to e.g. Podcasts/iTunes Store/All Podcasts but then there is no content.

Cheers

**Comment by tkem** [comment]
Hi @deisi,

first place to ask should usually be http://discuss.mopidy.com. 
What version if Mopidy and Mopidy-Podcast are you using? If you're running Mopidy v1.1, you should definitely upgrade Mopidy-Podcast to the latest version. There's a known bug in Mopidy-Podcast that sounds quite like this.

Otherwise, please have a look at the Mopidy logs, and post them here if anything looks suspicious. See docs.mopidy.com for general troubleshooting information.

**Comment by deisi** [comment]
I use Mopidy 1.1.0 and mopidy-podcast i cloned from git and installed with

    python2 setup.py build
    python2 setup.py install

http://pastebin.com/XkzQ5arW here is a mopidy.log from my setup but I don't see anything in there.

**Comment by tkem** [comment]
Ah, OK ;-)
Was completely baffled first, since I copy-pasted your config into my own `mopidy.conf` and I could browse without problems. But then I had a look at your logs and saw you had Moped installed...
Would you please try another Web and/or MPD client and see if the problem persists. I tried Mopidy-Mobile, MusicBox WebClient, mpc and ncmpcpp, and they all seem to work.

**Comment by deisi** [comment]
Here we go. Now its working. Thanks a lot. Never would have thought of this.

**Comment by tkem** [comment]
Good. If you'd like Moped to work with this, I'd kindly suggest you file a bug report on https://github.com/martijnboland/moped/issues.

**Comment by deisi** [comment]
Okay I will do it this evening.

**Comment by deisi** [comment]
[here](https://github.com/martijnboland/moped/issues/56) is the link to the issue in the moped issue tracker.

**Comment by tkem** [comment]
Great, thanks a lot! I don't know about the state of Moped development, but if this works with multiple other clients, this may be something the developer(s) may want to look into...
