### ISSUE TITLE
Cannot access Cloudfare-hosted podcasts via HTTPS

### ISSUE THREAD

**Issue by kdbdallas** [tkem/mopidy-podcast#31]
Everything works great until I pass it a URL of a podcast that is being hosted behind https.
Then it won't load and spits out HTTP Error 403: Forbidden errors.
However if I try loading it in my browser or pulling it with wget it pulls down just fine.
An example podcast/url is: https://www.relay.fm/radar/feed
Unfortunately it is not available in non-SSL so just going that route is not an option (plus I have about 4 other shows with this same issue) 
If you want more examples, it seems like relay.fm hosts all their shows feeds on https.

**Comment by tkem** [comment]
Strange. However, I doubt this has something to do with HTTPS, but more probably with the relay.fm server, since

- if it was an HTTPS problem, you'd probably get no connection at all instead of a 403 error, except maybe if Mopidy-Podcast was using plain HTTP maybe, which AFAICS it isn't.

- accessing other podcasts using HTTPS seem to work, for example https://isc.sans.edu/dailypodcast.xml (just the first thing that came up on Google when searching for "Podcast" and "HTTPS").

May I suggest that you try some other, non-`relay.fm` based podcasts with HTTPS? If the problem persists independently of the hosting site, I'll look into this more deeply. Otherwise, I think only the relay.fm site admin can tell what produces that 403 error (unsupported user agent header, or whatever).

**Comment by kdbdallas** [comment]
I will talk to him and see if he will debug it with me.
Thanks!

**Comment by tkem** [comment]
Well, couldn't resist, and it looks like relay.fm is using Cloudfare which apparently has some issues with Python's `urllib` which Mopidy-Podcast uses for retrieving RSS feeds:
```
curl -D- https://www.relay.fm/radar/feed
HTTP/1.1 200 OK
Server: cloudflare-nginx
...
```
Just google "cloudfare blocking urllib" or something like that, and you will get quite a few results, some suggesting to turn of Cloudfare's browser checking, and some saying that this was a bug that has already been fixed in Cloudfare (but probably not in the version that relay.fm is using).

**Comment by tkem** [comment]
Not much we can do here, I guess...
