### ISSUE TITLE
Weird playlist issue

### ISSUE THREAD

**Issue by gerroon** [tkem/mopidy-podcast#48]
Hi

I like this addon alot but I am having one issue with it. If I click on an episode, it starts playing which is what I want. Then I stop the episode and start playing an internet radio or an audio file, the new media does not play instead, the podcast just resumes. I am not sure why that is the case. Maybe there is a difference in the playlist behavior, or some other thing is failing. 

I use Mopid 2.1.0 on Debian Testing X64 , with Mopidy Mobile

**Comment by jjok** [comment]
That sounds like it's an issue with the client/front-end that you're using, rather than an issue with this extension.

**Comment by gerroon** [comment]
Hi

I am not sure. I have the saame issue with Musicbox web client as well. Somehow the new media is not replacing the podcast item in the queue, sometimes it will still play the podcast item even the podcast episode does not seem to be in the queue or currently playing.

I am not saying it is the podcast extension. I thought that I would mention it here first.


thanks

**Comment by tkem** [comment]
Mopidy-Podcast has no control over Mopidy's play queue, so I doubt this is really a Mopidy-Podcast issue. I'd suggest posting your issue to https://discourse.mopidy.com/, since this is read by more people than the extension developer and @jjok (thanks, by the way!). Exact steps to reproduce your problem, including version number and actual podcast URLs and what kind of "new media" is not replacing the podcast, would also be appreciated there, I think.
