### ISSUE TITLE
Unable to play any podcast

### ISSUE THREAD

**Issue by AdmiralStipe** [tkem/mopidy-podcast#59]
I imported Podcasts.opml from my Android app (Podcast Addict), placed it in config folder and Mopidy can read it allright, listing all subscribed podcasts. 
But whenever I choose a podcast to play, I get an error, flashed in red "Mopidy: Failed to add some tracks". Additionally, if I check the Track Info, I get (this is example of one podcast, but's it's the same with different URI for all of them) "Could not find anything with URI podcast+https://metinalista.si/category/ldgd/feed/%23https://metinalista.si/?p=34343". 
Is there something missing in my config or an actual bug?
I'm running Mopidy on Raspberry Pi 4B and apart from this issue with Podcast addon everything else works as expected.

**Comment by tkem** [comment]
Stripping the "podcast+" Prefix, what we get from [https://metinalista.si/category/ldgd/feed/%23https://metinalista.si/?p=34343](https://metinalista.si/category/ldgd/feed/%23https://metinalista.si/?p=34343) is an HTTP Redirect:
```
$ curl -D- 'https://metinalista.si/category/ldgd/feed/%23https://metinalista.si/?p=34343'
HTTP/2 301 
server: nginx
date: Tue, 09 Mar 2021 14:28:36 GMT
content-type: text/html; charset=UTF-8
content-length: 0
location: https://metinalista.si/ldgd-056-ne-vem/
x-cache-enabled: True
x-redirect-by: WordPress
x-httpd-modphp: 1
host-header: 6b7412fb82ca5edfd0917e3957f05d89
x-proxy-cache: MISS
x-proxy-cache-info: 0 NC:000000 UP:
```
When we follow that to the `location` [https://metinalista.si/ldgd-056-ne-vem/](https://metinalista.si/ldgd-056-ne-vem/), we get an HTML page, _not_ a valid RSS feed:
```
server: nginx
date: Tue, 09 Mar 2021 14:31:43 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
x-cache-enabled: True
link: <https://metinalista.si/wp-json/>; rel="https://api.w.org/"
link: <https://metinalista.si/wp-json/wp/v2/posts/34343>; rel="alternate"; type="application/json"
link: <https://metinalista.si/?p=34343>; rel=shortlink
x-httpd-modphp: 1
host-header: 8441280b0c35cbc1147f8ba998a563a7
x-proxy-cache: HIT
```
So this won't work. No way. Since you say you exported this from Podcast Addict, maybe that app uses some method to extract audio from Web pages, I don't know. But this URI does not point at anything `mopidy-podcast` can handle.

**Comment by AdmiralStipe** [comment]
OK, thx for your prompt answer... will try to compose the oppl manually with actual RSS sources... may I leave this issue open for now, if I have additional questions?

**Comment by tkem** [comment]
Sure, please also let me know if you find something out about how your app handles these...

**Comment by AdmiralStipe** [comment]
Before I start inventing warm water... does this opml file (directly exported from Podcast Addict) seem OK? It seems good to me, so I don't understand, how Mopidy changes the URI to the actual episode...
[Podcasts.opml.txt](https://github.com/tkem/mopidy-podcast/files/6110372/Podcasts.opml.txt)

Also f.e. for "Wathcmen podcast" I get the error: 
Could not find anything with URI podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast%23b0357c6c-1cec-11ea-b3c1-c72df08c614a
but the link for Watchmen in OPML actually point to RSS... 

Seems like Mopidy makes the URI from <![CDATA[ b0357c6c-1cec-11ea-b3c1-c72df08c614a ]]> instead of from <enclosure...>
Sorry, I may talk rubbish, since I don't know, how exactly this works... but I don't really know how to make a different OPML than the original one, so it will work...

**Comment by tkem** [comment]
@AdmiralStipe Sorry, I think I got somewhat confused here - it's been some time since I've been working on mopidy-podcast...

Thanks for your Podcasts.opml - it works fine on my Mopidy installation. I can't make much sense of the LD;GD podcast, but all episodes seem to play fine, so does the Watchmen podcast.

And yes, Mopidy-Podcast indeed uses the GUID from the feed to reference individual episodes, so it can access the metadata (title, artist, etc.) for individual episodes. However, these track URIs should look like `podcast+{podcast-uri}#{episode-guid}`, e.g.
```
podcast+https://metinalista.si/category/ldgd/feed/#https://metinalista.si/?p=34343
```
whereas probably your _client_ seems to encode the `#` in
```
podcast+https://metinalista.si/category/ldgd/feed/%23https://metinalista.si/?p=34343
```
I'm using Mopidy 3.1.1 with Mopidy-Podcast 3.0.0 and Mopidy-Mobile 1.10.0 as a client. However, command-line `mpc` client also preserves the `#` in URIs:
```
$ mpc add 'podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast'
$ mpc playlist
HBO - The Official Watchmen Podcast is coming Nov 3
HBO - Masks (Episodes 1-3)
HBO - Nostalgia (Episodes 4 - 6)
HBO - Eggs (Episodes 7 - 9)
HBO - Introducing “Lovecraft Country Radio”
HBO - Interview with Directors Nicole Kassell and Stephen Williams
HBO - Interview with Writers Lila Byock, Christal Henry, and Stacy Osei-Kuffour
$ mpc -f '%file%' playlist
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#fa1d3314-f772-11e9-a983-e7bd269df017
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#e5365856-fc2a-11e9-bb68-63f5b3f2145a
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#ba8cd086-0b1a-11ea-aa39-cfba8b7eb671
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#b0357c6c-1cec-11ea-b3c1-c72df08c614a
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#f7273140-df26-11ea-8d6a-4b2a416bf846
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#7912191e-e3db-11ea-831c-83296d8cf24a
podcast+https://feeds.megaphone.fm/theofficialwatchmenpodcast#002939e4-e730-11ea-a5a3-3bd7b74465c1
$ mpc play
volume:100%   repeat: off   random: off   single: off   consume: off
```
So my best bet is this has something to do with your client...

**Comment by tkem** [comment]
Update: I also tried with the Mopidy-MusicBox-Webclient (so I don't sound too biased), and it also plays Podcasts from the OPML file without any issues, AFAICS.

**Comment by AdmiralStipe** [comment]
I'm using Mopidy server 3.56.1 and for Mopidy-Podcast I can't say (not sure where to check - I installed it today, so I guess it's the last available version) and the client (for now) is Mopidy Iris (also not sure which version, I assume the latest one)... 
On the long term I want to control it from Homeassistant with an addon client (https://github.com/bushvin/hass-integrations), but that's a distant future as for now I have no idea how to get to the Podcast addon from Homeassistant addon, which for now only plays playlists from Mopidy :). 

So any hints on how to proceed then? Where to start "digging" in Iris or maybe use another client to create playlists from podcast feeds?

**Comment by AdmiralStipe** [comment]
OK, disregard my last message... made it running with MusicBox Webclient without problems... obviously Iris doesn't want to cooperate, but MusixBox does :). 
So, for now it's OK, now I'm on a long run to make it work from Homeassistant :).

**Comment by tkem** [comment]
@AdmiralStipe: Great! And good luck with your home assistant integration!
